# Añade tildes y eñes a strings visibles del frontend (apps/web/**).
# NO toca apps/api/** ni node_modules / .next.
# Como el archivo no lleva BOM, se lee con [System.IO.File]::ReadAllText(..., UTF8)
# para que PS 5.1 no confunda UTF-8 con Windows-1252.
$ErrorActionPreference = 'Stop'
$root = 'd:\Desarrollo de aplicaciones Web avanzado\proyecto'
Set-Location $root

# Mapa: clave -> valor con tilde/enhe. Las claves mas largas van primero
# para que un reemplazo corto no "robe" texto de una clave larga
# (p.ej. "Albumes" antes que "Album").
$map = [ordered]@{}
$pairs = @(
  @{k='Cancelaciones';v='Cancelaciones'},
  @{k='cancelaciones';v='cancelaciones'},
  @{k='Reservaciones';v='Reservaciones'},
  @{k='reservaciones';v='reservaciones'},
  @{k='Notificaciones';v='Notificaciones'},
  @{k='notificaciones';v='notificaciones'},
  @{k='Calificaciones';v='Calificaciones'},
  @{k='calificaciones';v='calificaciones'},
  @{k='Confirmaciones';v='Confirmaciones'},
  @{k='confirmaciones';v='confirmaciones'},
  @{k='Direcciones';v='Direcciones'},
  @{k='direcciones';v='direcciones'},
  @{k='Descripciones';v='Descripciones'},
  @{k='descripciones';v='descripciones'},
  @{k='Informacion';v='Información'},
  @{k='informacion';v='información'},
  @{k='Cancelo';v='Canceló'},
  @{k='cancelo';v='canceló'},
  @{k='Cancelacion';v='Cancelación'},
  @{k='cancelacion';v='cancelación'},
  @{k='Cancelado';v='Cancelado'},
  @{k='cancelado';v='cancelado'},
  @{k='Cancelar';v='Cancelar'},
  @{k='cancelar';v='cancelar'},
  @{k='Confirmacion';v='Confirmación'},
  @{k='confirmacion';v='confirmación'},
  @{k='Confirmado';v='Confirmado'},
  @{k='confirmado';v='confirmado'},
  @{k='Confirmar';v='Confirmar'},
  @{k='confirmar';v='confirmar'},
  @{k='Resena';v='Reseña'},
  @{k='resena';v='reseña'},
  @{k='Resenas';v='Reseñas'},
  @{k='resenas';v='reseñas'},
  @{k='Albumes';v='Álbumes'},
  @{k='albumes';v='álbumes'},
  @{k='Album';v='Álbum'},
  @{k='album';v='álbum'},
  @{k='Sesiones';v='Sesiones'},
  @{k='sesiones';v='sesiones'},
  @{k='Sesion';v='Sesión'},
  @{k='sesion';v='sesión'},
  @{k='Region';v='Región'},
  @{k='region';v='región'},
  @{k='Atencion';v='Atención'},
  @{k='atencion';v='atención'},
  @{k='Direccion';v='Dirección'},
  @{k='direccion';v='dirección'},
  @{k='Contrasena';v='Contraseña'},
  @{k='contrasena';v='contraseña'},
  @{k='Telefono';v='Teléfono'},
  @{k='telefono';v='teléfono'},
  @{k='Manana';v='Mañana'},
  @{k='manana';v='mañana'},
  @{k='Pequeno';v='Pequeño'},
  @{k='pequeno';v='pequeño'},
  @{k='Pequena';v='Pequeña'},
  @{k='pequena';v='pequeña'},
  @{k='Minimas';v='Mínimas'},
  @{k='minimas';v='mínimas'},
  @{k='Minimos';v='Mínimos'},
  @{k='minimos';v='mínimos'},
  @{k='Minima';v='Mínima'},
  @{k='minima';v='mínima'},
  @{k='Minimo';v='Mínimo'},
  @{k='minimo';v='mínimo'},
  @{k='Compania';v='Compañía'},
  @{k='compania';v='compañía'},
  @{k='Diseno';v='Diseño'},
  @{k='diseno';v='diseño'},
  @{k='Dueno';v='Dueño'},
  @{k='dueno';v='dueño'},
  @{k='Puntuacion';v='Puntuación'},
  @{k='puntuacion';v='puntuación'},
  @{k='Calificacion';v='Calificación'},
  @{k='calificacion';v='calificación'},
  @{k='Opinion';v='Opinión'},
  @{k='opinion';v='opinión'},
  @{k='Anios';v='Años'},
  @{k='anios';v='años'},
  @{k='Anio';v='Año'},
  @{k='anio';v='año'},
  @{k='Tambien';v='También'},
  @{k='tambien';v='también'},
  @{k='Categorias';v='Categorías'},
  @{k='categorias';v='categorías'},
  @{k='Categoria';v='Categoría'},
  @{k='categoria';v='categoría'},
  @{k='Botones';v='Botones'},
  @{k='botones';v='botones'},
  @{k='Boton';v='Botón'},
  @{k='boton';v='botón'},
  @{k='Numeros';v='Números'},
  @{k='numeros';v='números'},
  @{k='Numero';v='Número'},
  @{k='numero';v='número'},
  @{k='Reunion';v='Reunión'},
  @{k='reunion';v='reunión'},
  @{k='Gestion';v='Gestión'},
  @{k='gestion';v='gestión'},
  @{k='Peluquerias';v='Peluquerías'},
  @{k='peluquerias';v='peluquerías'},
  @{k='Peluqueria';v='Peluquería'},
  @{k='peluqueria';v='peluquería'},
  @{k='Dias';v='Días'},
  @{k='dias';v='días'},
  @{k='Dia';v='Día'},
  @{k='dia';v='día'},
  @{k='Rapida';v='Rápida'},
  @{k='rapida';v='rápida'},
  @{k='Rapido';v='Rápido'},
  @{k='rapido';v='rápido'},
  @{k='Ultimas';v='Últimas'},
  @{k='ultimas';v='últimas'},
  @{k='Ultimos';v='Últimos'},
  @{k='ultimos';v='últimos'},
  @{k='Ultima';v='Última'},
  @{k='ultima';v='última'},
  @{k='Ultimo';v='Último'},
  @{k='ultimo';v='último'},
  @{k='Galerias';v='Galerías'},
  @{k='galerias';v='galerías'},
  @{k='Galeria';v='Galería'},
  @{k='galeria';v='galería'},
  @{k='Cumpleanos';v='Cumpleaños'},
  @{k='cumpleanos';v='cumpleaños'},
  @{k='Tamanos';v='Tamaños'},
  @{k='tamanos';v='tamaños'},
  @{k='Tamanio';v='Tamaño'},
  @{k='tamanio';v='tamaño'},
  @{k='Mision';v='Misión'},
  @{k='mision';v='misión'},
  @{k='Vision';v='Visión'},
  @{k='vision';v='visión'},
  @{k='Cortesias';v='Cortesías'},
  @{k='cortesias';v='cortesías'},
  @{k='Cortesia';v='Cortesía'},
  @{k='cortesia';v='cortesía'},
  @{k='Imagenes';v='Imágenes'},
  @{k='imagenes';v='imágenes'},
  @{k='Espanol';v='Español'},
  @{k='espanol';v='español'},
  @{k='publicamente';v='públicamente'},
  @{k='publicas';v='públicas'},
  @{k='Publicas';v='Públicas'},
  @{k='publicos';v='públicos'},
  @{k='Publicos';v='Públicos'},
  @{k='publica';v='pública'},
  @{k='Publica';v='Pública'},
  @{k='publico';v='público'},
  @{k='Publico';v='Público'},
  @{k='tipicas';v='típicas'},
  @{k='Tipicas';v='Típicas'},
  @{k='tipicos';v='típicos'},
  @{k='Tipicos';v='Típicos'},
  @{k='tipica';v='típica'},
  @{k='Tipica';v='Típica'},
  @{k='tipico';v='típico'},
  @{k='Tipico';v='Típico'},
  @{k='dificil';v='difícil'},
  @{k='Dificil';v='Difícil'},
  @{k='facil';v='fácil'},
  @{k='Facil';v='Fácil'},
  @{k='unicas';v='únicas'},
  @{k='Unicas';v='Únicas'},
  @{k='unicos';v='únicos'},
  @{k='Unicos';v='Únicos'},
  @{k='unica';v='única'},
  @{k='Unica';v='Única'},
  @{k='unico';v='único'},
  @{k='Unico';v='Único'},
  @{k='maximas';v='máximas'},
  @{k='Maximas';v='Máximas'},
  @{k='maximos';v='máximos'},
  @{k='Maximos';v='Máximos'},
  @{k='maxima';v='máxima'},
  @{k='Maxima';v='Máxima'},
  @{k='maximo';v='máximo'},
  @{k='Maximo';v='Máximo'},
  @{k='sera';v='será'},
  @{k='Sera';v='Será'},
  @{k='estara';v='estará'},
  @{k='Estara';v='Estará'},
  @{k='podra';v='podrá'},
  @{k='Podra';v='Podrá'},
  @{k='tendra';v='tendrá'},
  @{k='Tendra';v='Tendrá'},
  @{k='logica';v='lógica'},
  @{k='Logica';v='Lógica'},
  @{k='logico';v='lógico'},
  @{k='Logico';v='Lógico'},
  @{k='periodo';v='período'},
  @{k='Periodo';v='Período'},
  @{k='periodos';v='períodos'},
  @{k='Periodos';v='Períodos'},
  @{k='practicas';v='prácticas'},
  @{k='Practicas';v='Prácticas'},
  @{k='practicos';v='prácticos'},
  @{k='Practicos';v='Prácticos'},
  @{k='practica';v='práctica'},
  @{k='Practica';v='Práctica'},
  @{k='practico';v='práctico'},
  @{k='Practico';v='Práctico'},
  @{k='cuantos';v='cuántos'},
  @{k='Cuantos';v='Cuántos'},
  @{k='cuantas';v='cuántas'},
  @{k='Cuantas';v='Cuántas'},
  @{k='cuanto';v='cuánto'},
  @{k='Cuanto';v='Cuánto'},
  @{k='cuanta';v='cuánta'},
  @{k='Cuanta';v='Cuánta'},
  @{k='cuales';v='cuáles'},
  @{k='Cuales';v='Cuáles'},
  @{k='cual';v='cuál'},
  @{k='Cual';v='Cuál'},
  @{k='como';v='cómo'},
  @{k='Como';v='Cómo'},
  @{k='donde';v='dónde'},
  @{k='Donde';v='Dónde'},
  @{k='cuando';v='cuándo'},
  @{k='Cuando';v='Cuándo'},
  @{k='quienes';v='quiénes'},
  @{k='Quienes';v='Quiénes'},
  @{k='quien';v='quién'},
  @{k='Quien';v='Quién'},
  @{k='segun';v='según'},
  @{k='Segun';v='Según'},
  @{k='rapidas';v='rápidas'},
  @{k='Rapidas';v='Rápidas'},
  @{k='rapidos';v='rápidos'},
  @{k='Rapidos';v='Rápidos'},
  @{k='tambien';v='también'},
  @{k='Tambien';v='También'}
)
foreach ($p in $pairs) { if ($p.k -ne $p.v -and -not $map.Contains($p.k)) { $map[$p.k] = $p.v } }
Write-Host ('[info] {0} pares cargados' -f $map.Count)

$utf8 = [System.Text.Encoding]::UTF8
$targets = Get-ChildItem -Path 'apps\web' -Recurse -Include *.ts,*.tsx,*.css,*.html -File |
  Where-Object {
    $_.FullName -notmatch 'node_modules' -and
    $_.FullName -notmatch '\\.next\\' -and
    $_.FullName -notmatch '\\dist\\'
  }

$totalChanged = 0
$fileReports = @()

foreach ($file in $targets) {
  $orig = [System.IO.File]::ReadAllText($file.FullName, $utf8)
  $next = $orig
  $fileHits = 0
  foreach ($k in $map.Keys) {
    $v = $map[$k]
    $pattern = '(?<![A-Za-zÁÉÍÓÚáéíóúÑñÜü])' + [regex]::Escape($k) + '(?![A-Za-zÁÉÍÓÚáéíóúÑñÜü])'
    $count = ([regex]::Matches($next, $pattern)).Count
    if ($count -gt 0) {
      $next = [regex]::Replace($next, $pattern, $v)
      $fileHits += $count
    }
  }
  if ($fileHits -gt 0) {
    [System.IO.File]::WriteAllText($file.FullName, $next, $utf8)
    $rel = $file.FullName.Substring($root.Length + 1)
    $fileReports += [pscustomobject]@{ File = $rel; Hits = $fileHits }
    $totalChanged += $fileHits
    Write-Host ('[changed] {0}  (+{1})' -f $rel, $fileHits)
  }
}

Write-Host ''
Write-Host ('[done] {0} sustituciones en {1} archivos' -f $totalChanged, $fileReports.Count)
$fileReports | Sort-Object Hits -Descending | Format-Table -AutoSize | Out-String | Write-Host
